### PR TITLE
Add typo checking to PR CI

### PR DESCRIPTION
**Pull request by ciaranevans**
# What I am changing

TL;DR: This PR adds `crate-ci/typos` as an Action to check for typos in PRs to this repository (Currently only doing `.md` files...)

# How I did it

* `.github/workflows/check-pr-for-typos.yaml`:
  * Create new `Check PR docs for typos` workflow

# How you can test it

Simply (I hope) raise a PR with bad spelling in your `.md` files

Signed-off-by: Ciaran Evans <ciaran@reliably.com>

### CODE REVIEW

**Comment by xaah** [comment]
@ciaranevans maybe the readme could be updated with what to do in false positive cases. Also, if there is additional setup to support the false positives file, that might be important to already have setup as well. I think there are bound to be quite a few words that are technical words that haven't reached the dictionary yet. https://github.com/crate-ci/typos#false-positives

**Comment by ciaranevans** [comment]
@xaah sure sounds good!

I'm just trying to make sure it's actually checking all the `.md`'s at the mo, it's missing the ones I've purposefully made

**Comment by ciaranevans** [comment]
@xaah et al, gonna leave this for the mo, it's not picking up really obvious mistakes, I've raised an issue on their repo to see what is happening there. 

Also asked around to see if friends know of a good alternative

**Comment by xaah** [comment]
@ciaranevans I think a decent amount of the mistakes would not be picked up by that type of checker anyway. I believe Grant used a Grammarly plug-in that was used whilst coding docs which might be a more wholesome solution albeit not a solution to prevent someone merging the mistakes. If you find a solution for that maybe some guidance on the readme file could help. I haven't tried this but maybe https://marketplace.visualstudio.com/items?itemName=znck.grammarly

**Comment by ciaranevans** [comment]
Closing for now, I might revisit this in the future - Looks like the tool I used did some large updates to their lists of words: https://github.com/crate-ci/typos/issues/312#issuecomment-887809241

**Pull request closed without merging**
